name: 'Build Docs'
description: 'Build and optionally deploy docs'

inputs:
  source-path:
    default: '.'
  strict:
    default: 'false'
  deploy-version:
    required: false
  deploy-alias:
    required: false

runs:
  using: 'composite'
  steps:
    - name: Create python virtual env
      working-directory: ${{ inputs.source-path }}
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-venv
        python3 -m venv .venv
        echo "$(pwd)/.venv/bin" >> "$GITHUB_PATH"
      shell: bash

    - name: Install dependencies
      working-directory: ${{ inputs.source-path }}
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash

    - name: Build docs
      working-directory: ${{ inputs.source-path }}
      env:
        STRICT: ${{ inputs.strict }}
      run: |
        if [[ "$STRICT" == 'true' ]]; then
          strict_flags="--strict"
        fi

        mkdocs build ${strict_flags+"${strict_flags}"}
      shell: bash

    - name: Deploy to Github Pages
      working-directory: ${{ inputs.source-path }}
      if: inputs.deploy-version && inputs.deploy-alias
      env:
        DEPLOY_VERSION: ${{ inputs.deploy-version }}
        DEPLOY_ALIAS: ${{ inputs.deploy-alias }}
      run: |
        git config --global \
          user.name "github-actions[bot]"
        git config --global \
          user.email "41898282+github-actions[bot]@users.noreply.github.com"

        mike deploy --push --update-aliases "$DEPLOY_VERSION" "$DEPLOY_ALIAS"
      shell: bash
