users:
  ananos:
    name: Anastassios Nanos
    email: ananos@nubificus.co.uk
  jlcsf:
    name: Jay Limachya
    email: jlima@nubificus.co.uk
  cmainas:
    name: Charalampos Mainas
    email: cmainas@nubificus.co.uk
  gkoletsos:
    name: George Koletsos
    email: gkol@nubificus.co.uk
  gntouts:
    name: Georgios Ntoutsos
    email: gntouts@nubificus.co.uk
  johnp41:
    name: Ioannis Plakas
    email: iplakas@nubificus.co.uk
  JoshuaQSH:
    name: Shenghao Qiu
    email: shenghao@nubificus.co.uk
  marrgko:
    name: Maria Goutha
    email: mgouth@nubificus.co.uk
  panosmaurikos:
    name: Panos Mavrikos
    email: pmavrikos@nubificus.co.uk
  ale161:
    name: Alexandros Karantzoulis
    email: akaran@nubificus.co.uk
  ilagomatis:
    name: Ilias Lagomatis
    email: ilago@nubificus.co.uk
