[default.extend-identifiers]
ScatterND = "ScatterND"

[default.extend-words]
ba = "ba"

[files]
extend-exclude = [
  "docs/language-bindings/python-bindings/api-reference/**",
  "docs/assets/**",
  "outdated_docs/**",
]
