name: Build and Deploy to Github Pages

on:
  push:
    branches: [main]
    tags: ["v*"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions: read-all

jobs:
  build-and-deploy:
    name: Build and Deploy
    uses: ./.github/workflows/verify-build.yml
    with:
      deploy: true
    secrets: inherit

  update-release:
    needs: build-and-deploy
    name: Update Release
    if: always()
    uses: nubificus/vaccel/.github/workflows/update-release.yml@main
    with:
      create-github-release: false
      result: ${{ needs.build-and-deploy.result }}
    secrets: inherit
