name: Build and Deploy to Github Pages

on:
  push:
    branches: [main]
    tags: ["v*"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions: read-all

jobs:
  build-and-deploy:
    name: Build and Deploy
    uses: ./.github/workflows/verify-build.yml
    with:
      deploy: true
    secrets: inherit
