name: "Check Spelling/Links"

on:
  pull_request:
    branches:
       - main

jobs:
  check:
    runs-on: [self-hosted, x86_64, go]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            **/*.md

      - name: Check if any Markdown file was changed
        if: steps.changed-files.outputs.any_changed == 'false'
        run: |
          echo "No Markdown files were changed"
          exit 0

      - name: Spellcheck
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: crate-ci/typos@master
        with:
          config: .github/linters/typos.toml
          files: ${{ steps.changed-files.outputs.all_changed_files }}

#      - name: Check links
#        uses: umbrelladocs/action-linkspector@v1
#        with:
#          #github_token: ${{ secrets.github_token }}
#          #reporter: github-pr-review
#          config_file: .github/linters/linkspector.toml
#          fail_on_error: true

      - name: Check links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-verbose-mode: 'yes'
          folder-path: 'docs'

