name: Trigger Checks

on:
  pull_request:
    branches: ["main"]
    types: [opened]

concurrency:
  group: >-
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: read-all

env:
  ACTIONS_REPO: 'nubificus/vaccel'
  ACTIONS_REF: 'main'

jobs:
  trigger-checks:
    name: Trigger Checks
    runs-on: base-2204-amd64
    steps:
      - name: Parse repository names
        id: parse-repos
        run: |
          {
            echo "repo-name=$(basename "$GITHUB_REPOSITORY")"
            echo "actions-repo-name=$(basename "$ACTIONS_REPO")"
          } >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Generate initialization vaccel-bot token
        id: generate-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.VACCEL_BOT_CLIENT_ID }}
          private-key: ${{ secrets.VACCEL_BOT_PRIVATE_KEY }}
          repositories: |
            ${{ steps.parse-repos.outputs.repo-name }}
            ${{ steps.parse-repos.outputs.actions-repo-name }}
          permission-contents: read

      - name: Checkout .github directory
        uses: actions/checkout@v6
        with:
          sparse-checkout: .github
          repository: ${{ env.ACTIONS_REPO }}
          ref: ${{ env.ACTIONS_REF }}
          token: ${{ steps.generate-token.outputs.token }}

      - name: Initialize workspace
        uses: ./.github/actions/initialize-workspace
        with:
          remote-actions-repo: ${{ env.ACTIONS_REPO }}
          submodules: 'false'
          dot-github-only: 'true'
          token: ${{ steps.generate-token.outputs.token }}

      - name: Generate trigger vaccel-bot token
        id: generate-trigger-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.VACCEL_BOT_CLIENT_ID }}
          private-key: ${{ secrets.VACCEL_BOT_PRIVATE_KEY }}
          repositories: ${{ steps.parse-repos.outputs.repo-name }}
          permission-contents: read
          permission-pull-requests: write

      - name: Trigger checks
        uses: ./.github/actions/add-or-remove-pr-label
        with:
          issue-number: ${{ github.event.pull_request.number }}
          label: 'ok-to-test'
          token: ${{ steps.generate-trigger-token.outputs.token }}
