name: "Spellcheck"

on:
  pull_request:
    branches:
       - main

jobs:
  spellcheck:
    runs-on: [self-hosted, x86_64, go]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            **/*.md

      - name: Check if any Markdown file was changed
        if: steps.changed-files.outputs.any_changed == 'false'
        run: |
          echo "No Markdown files were changed"
          exit 0

      - name: Spellcheck
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: crate-ci/typos@master
        with:
          config: .github/linters/typos.toml
          files: ${{ steps.changed-files.outputs.all_changed_files }}

          #- name: Check links with linkcheck
          #uses: filiph/linkcheck@3.0.0

          #- name: Run linkspector
          #uses: umbrelladocs/action-linkspector@v1
          #with:
          ##github_token: ${{ secrets.github_token }}
          #reporter: github-pr-review
          #fail_on_error: true


      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-verbose-mode: 'yes'
          folder-path: 'docs' #, md/dir2'
          #file-path: './README.md, ./LICENSE, ./md/file4.markdown'

