name: Verify Links

on:
  workflow_call:
    inputs:
      actions-repo:
        type: string
        default: 'nubificus/vaccel'
      actions-ref:
        type: string
        default: 'main'
    secrets:
      VACCEL_BOT_PRIVATE_KEY:
        required: false

permissions: read-all

jobs:
  verify-links:
    name: Verify Links
    runs-on: base-dind-2204-amd64
    steps:
      - name: Checkout .gitmodules
        uses: actions/checkout@v6
        with:
          sparse-checkout: .gitmodules

      - name: Parse repository names
        id: parse-repos
        env:
          ACTIONS_REPO: ${{ inputs.actions-repo }}
        run: |
          submodule_names=$(git config --file .gitmodules \
            --get-regexp '\.url$' |
            awk -F'/' '{sub(/\.git$/, "", $NF); print $NF}')

          {
            echo "repo-name=$(basename "$GITHUB_REPOSITORY")"
            echo "actions-repo-name=$(basename "$ACTIONS_REPO")"
            echo 'submodule-names<<EOF'
            echo "$submodule_names"
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Generate vaccel-bot token
        id: generate-token
        if: vars.VACCEL_BOT_CLIENT_ID
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.VACCEL_BOT_CLIENT_ID }}
          private-key: ${{ secrets.VACCEL_BOT_PRIVATE_KEY }}
          repositories: |
            ${{ steps.parse-repos.outputs.repo-name }}
            ${{ steps.parse-repos.outputs.actions-repo-name }}
            ${{ steps.parse-repos.outputs.submodule-names }}
          permission-contents: read

      - name: Checkout remote .github directory
        uses: actions/checkout@v6
        with:
          sparse-checkout: .github
          repository: ${{ inputs.actions-repo }}
          ref: ${{ inputs.actions-ref }}
          token: ${{ steps.generate-token.outputs.token || github.token }}

      - name: Initialize workspace
        uses: ./.github/actions/initialize-workspace
        with:
          remote-actions-repo: ${{ inputs.actions-repo }}
          submodules: 'true'
          token: ${{ steps.generate-token.outputs.token || github.token }}

      - name: Build docs
        uses: ./.github/actions/build-docs

      - name: Check markdown links w/o macros
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --retry-wait-time 10
            --exclude '\[\[\s*.*?\s*\]\]'
            --exclude-path docs/language-bindings/python-bindings/api-reference
            docs

      - name: Set excluded patterns
        run: |
          site_url_esc=$(sed 's/[.[\()*+?^${}|\&\/]/\\&/g' docs/CNAME)
          echo "SITE_URL_ESC=${site_url_esc}" >> "$GITHUB_ENV"

      - name: Check external links in HTML
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --retry-wait-time 20
            --root-dir $(pwd)/site
            --exclude ^https://${{ env.SITE_URL_ESC }}
            site
